id: A1D99296D
title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
type: translation
pechas:
- IE88B69C9
- I54D70F2F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:23.073440
  last_modified_at: 2023-01-04 11:37:23.073447
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IE88B69C9/D30E: 8EB9
  I54D70F2F/DDD8: 8EB9
